### ISSUE TITLE
Handling for special global builtin modules

### ISSUE THREAD

**Issue by tmpfs** [LavaMoat/basalt#29]
There is some ambiguity on how we should handle builtin modules that are also exposed by `node` as globals such as:

* `process`
* `console`
* `performance` from `perf_hooks/performance`

The existing lavamoat policy generator puts them in globals which makes sense to me but what about when the builtin modules are explicitly imported, should they then exist in `builtin` instead of `globals`:

```javascript
// Explicit import of a builtin module that is also exposed as global
import process from 'process';
const foo = process.env.FOO;
```

/cc @kumavis

**Comment by kumavis** [comment]
i dont have any special handling here. if the ref is a global i add policy for the global, if its an import i set it as an import. in the example the process is not a global

**Comment by tmpfs** [comment]
That's all good and makes sense to me, I guess the caveat (at least with how I am handling this now) is that if the default import were renamed I would get a duplicate entry in `builtin` and `globals`:

```javascript
import ps from 'process';
const foo1 = ps.env.FOO;
const foo2 = process.env.FOO;
```

Yields:

```json
{
  "resources": {
    "import-builtins": {
      "builtin": {
        "process.env.FOO": true
      },
      "globals": {
        "process.env.FOO": true
      }
    }
  }
}
```

Is it worth detecting overlap between `globals` and `builtin` and filtering or is this duplication acceptable? 

I don't think it is a problem but we may want to remove these duplicates just to keep things tidy.
